language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
node_js:
  - "0.12"
  - "4.2"
after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
  - npm run semantic-release
